In [1]:
# Early depression detection - data analysis

In [2]:
import pandas as pd 

In [3]:
positive_data_train = pd.read_csv("positive_examples_train.csv")
negative_data_train = pd.read_csv("negative_examples_train.csv")
positive_data = pd.read_csv("positive_examples.csv") 
negative_data = pd.read_csv("negative_examples.csv")

positive_data['depressed'] = 1
negative_data['depressed'] = 0

In [4]:
positive_data

id                                              title  \
0      test_subject1345                                                NaN   
1      test_subject1345                                  Mid-Range Jumpers   
2      test_subject1345                                                NaN   
3      test_subject1345                                                NaN   
4      test_subject1345                                                NaN   
...                 ...                                                ...   
18724  test_subject9942                                                NaN   
18725  test_subject9942                                                NaN   
18726  test_subject9942                                                NaN   
18727  test_subject9942                                                NaN   
18728  test_subject9942  Christianity is not a religion (that is it has...   

                      date                                               text  \
0      2015-05-20 05:12:23                  So many unwanted Smith fadeaways.   
1      2015-05-20 04:56:18  Hey guys, Celtics fan here pulling hard for th...   
2      2015-05-01 05:51:20  Well he got 2 tonight so maybe he'll be able t...   
3      2015-04-30 13:49:51  I mean he'll get pinch hits and an occasional ...   
4      2015-04-30 05:47:34               Yeah you're probably right. Oh well.   
...                    ...                                                ...   
18724  2015-02-09 13:36:09  it is compelling, because suicide is a popular...   
18725  2015-02-09 13:31:32  you say you were raised Christian, you need to...   
18726  2015-02-09 13:26:23  I honestly couldn't think of title and I just ...   
18727  2015-02-09 13:20:55  not referring to those genres\n\nI mean what I...   
18728  2015-02-09 13:13:11  there are only 2 commandments as rules (there ...   

       depressed  
0              1  
1              1  
2              1  
3              1  
4              1  
...          ...  
18724          1  
18725          1  
18726          1  
18727          1  
18728          1  

[18729 rows x 5 columns]

In [5]:
pos_unique = positive_data_train['id'].drop_duplicates()
n_pos = len(pos_unique)
n_pos

83

In [6]:
neg_unique = negative_data_train['id'].drop_duplicates()
n_neg = len(neg_unique)
n_neg

403

In [7]:
# The overall error would be the
# mean of the p ERDE values.

In [8]:
# ERDE function
def evaluation_metric(y_pred,y_true):
    error = 0
    cfp, cfn, ctp, ctn = (n_pos)/(n_pos+n_neg),1, 1, 0
    for i in range(len(y_pred)):
        if y_pred[i]==1 and 0==y_true[i]:
            error+= cfp
        elif y_pred[i]==1 and 1==y_true[i]:
            error+= method(i)
        elif y_pred[i]==0 and 0==y_true[i]:
            continue
        elif y_pred[i]==0 and 1==y_true[i]:
            error+= cfn
        
def method(i):
    pass


In [9]:
#preparing data

In [10]:
import re
#cleaning unimportant stuff like links, etc..
positive_data_train['text'] = positive_data_train['text'].astype("str").map(str.strip)
positive_data_train['text'] = positive_data_train['text'].apply(lambda x: re.sub('  ', ' ', x.lower()))
positive_data_train['text'] = positive_data_train['text'].apply(lambda x: re.sub(r'http\S+', '', x)) 
positive_data_train['text'] = positive_data_train['text'].apply(lambda x: re.sub(r"www\S+", "", x)) 
positive_data_train['text'] = positive_data_train['text'].apply(lambda x: re.sub(r"@\S+", "", x)) 

negative_data_train['text'] = negative_data_train['text'].astype("str").map(str.strip)
negative_data_train['text'] = negative_data_train['text'].apply(lambda x: re.sub('  ', ' ', x.lower()))
negative_data_train['text'] = negative_data_train['text'].apply(lambda x: re.sub(r'http\S+', '', x)) 
negative_data_train['text'] = negative_data_train['text'].apply(lambda x: re.sub(r"www\S+", "", x)) 
negative_data_train['text'] = negative_data_train['text'].apply(lambda x: re.sub(r"@\S+", "", x))

#concating test data
data_test = pd.concat([positive_data,negative_data])
data_test['text'] = data_test['text'].astype("str").map(str.strip)
data_test['text'] = data_test['text'].apply(lambda x: re.sub('  ', ' ', x.lower()))
data_test['text'] = data_test['text'].apply(lambda x: re.sub(r'http\S+', '', x)) 
data_test['text'] = data_test['text'].apply(lambda x: re.sub(r"www\S+", "", x)) 
data_test['text'] = data_test['text'].apply(lambda x: re.sub(r"@\S+", "", x))




In [11]:
#lematizing
from nltk.stem import WordNetLemmatizer
positive_data_train['text_lem'] = [' '.join([WordNetLemmatizer().lemmatize(re.sub('[^A-Za-z]', '', line)) for line in lists.split()]).strip() for lists in positive_data_train['text']]
negative_data_train['text_lem'] = [' '.join([WordNetLemmatizer().lemmatize(re.sub('[^A-Za-z]', '', line)) for line in lists]).strip() for lists in negative_data_train['text']] 
data_test['text_lem'] = [' '.join([WordNetLemmatizer().lemmatize(re.sub('[^A-Za-z]', '', line)) for line in lists.split()]).strip() for lists in data_test['text']] 

In [12]:
#concat data 
positive_data_train['depressed'] = 1
negative_data_train['depressed'] = 0
data_train = pd.concat([positive_data_train,negative_data_train])

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
vectorizer = TfidfVectorizer(max_df=0.3, max_features=100, min_df=10, stop_words='english',ngram_range=(2,3), use_idf=True)
X = vectorizer.fit_transform(positive_data_train['text'])


In [16]:
print (X.toarray())
print (vectorizer.get_feature_names())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['10 minutes', '20 minutes', '30 minutes', 'best friend', 'big deal', 'couple years', 'depression anxiety', 'didn know', 'didn think', 'didn want', 'doesn make', 'doesn mean', 'doesn want', 'doesn work', 'don believe', 'don care', 'don feel', 'don know', 'don like', 'don mind', 'don need', 'don really', 'don remember', 'don think', 'don understand', 'don want', 'don worry', 'feel bad', 'feel better', 'feel free', 'feel like', 'feel way', 'feels like', 'felt like', 'good luck', 'good thing', 'hard time', 'hey guys', 'high school', 'just don', 'just feel', 'just got', 'just like', 'just need', 'just started', 'just want', 'just wanted', 'know just', 'know people', 'let know', 'like don', 'like just', 'like people', 'like said', 'little bit', 'll just', 'll try', 'long term', 'long time', 'look like', 'looks like', 'lot people', 'lot t

In [18]:
#extracting most important features from each model
def show_most_informative_features(vect, clf, n=20):
    feature_names = vect.get_feature_names()
    coefs_with_fns = sorted(zip(clf.coef_[0], feature_names))
    top = zip(coefs_with_fns[:n], coefs_with_fns[:-(n + 1):-1])
    for (coef_1, fn_1), (coef_2, fn_2) in top:
        print("\t%.4f\t%-15s\t\t%.4f\t%-15s" % (coef_1, fn_1, coef_2, fn_2))
        


In [ ]:
data_train_grouped = data_train.groupby(['id'], as_index=False).agg(lambda x: x.tolist())
data_train_grouped['text_lem'] = [' '.join(line) for line in lists]).strip() for lists in data_train_grouped['text']] 
data_test_grouped = data_test.groupby(['id'], as_index=False).agg(lambda x: x.tolist())
data_test_grouped['text_lem'] = [' '.join(lists).strip() for lists in data_test_grouped['text']] 


In [ ]:
data_train_grouped.loc[data_train_grouped.depressed.str[0]==1,'depressed']='1'
data_train_grouped.loc[data_train_grouped.depressed.str[0]==0,'depressed']='0'

In [ ]:
data_test_grouped.loc[data_test_grouped.depressed.str[0]==1,'depressed']='1'
data_test_grouped.loc[data_test_grouped.depressed.str[0]==0,'depressed']='0'

In [ ]:
predicted = text_clf_lr.predict(data_test_grouped.text_lem)

In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
# nltk.download('vader_lexicon')
# Sentiment score to be added to each users column
sid = SentimentIntensityAnalyzer()
positive_data_train['sent']= positive_data_train.text_lem.apply(lambda x:sid.polarity_scores(x)['compound'])
data_train['sentiment_compound_polarity']=data_train.text_lem.apply(lambda x:sid.polarity_scores(x)['compound'])
data_train['sentiment_neutral']=data_train.text_lem.apply(lambda x:sid.polarity_scores(x)['neu'])
data_train['sentiment_negative']=data_train.text_lem.apply(lambda x:sid.polarity_scores(x)['neg'])
data_train['sentiment_pos']=data_train.text_lem.apply(lambda x:sid.polarity_scores(x)['pos'])
data_train['sentiment_type']=''
data_train.loc[data_train.sentiment_compound_polarity>0,'sentiment_type']='POSITIVE'
data_train.loc[data_train.sentiment_compound_polarity==0,'sentiment_type']='NEUTRAL'
data_train.loc[data_train.sentiment_compound_polarity<0,'sentiment_type']='NEGATIVE'

In [ ]:
data_train_sentiment_depressed = data_train.loc[:,['depressed','sentiment_neutral', 'sentiment_type', 'text', 'text_lem']]
data_train_sentiment_depressed = data_train_sentiment_depressed[data_train_sentiment_depressed.depressed == 1]

# Plotting 
data_train_sentiment = data_train_sentiment_depressed.groupby(['sentiment_type'])['sentiment_neutral'].count()
data_train_sentiment.rename("",inplace=True)
explode = (1, 0, 0)
plt.subplot(221)
data_train_sentiment.transpose().plot(kind='barh',figsize=(20, 20))
plt.title('Sentiment of Tweets by Depressed People', bbox={'facecolor':'0.8', 'pad':0})

In [ ]:
data_train_sentiment_not_depressed = data_train.loc[:,['depressed','sentiment_neutral', 'sentiment_type', 'text', 'text_lem']]
data_train_sentiment_not_depressed = data_train_sentiment_not_depressed[data_train_sentiment_not_depressed.depressed == 0]
data_train_sentiment = data_train_sentiment_not_depressed.groupby(['sentiment_type'])['sentiment_neutral'].count()
data_train_sentiment.rename("",inplace=True)
explode = (1, 0, 0)
plt.subplot(221)
data_train_sentiment.transpose().plot(kind='barh',figsize=(20, 20))
plt.title('Sentiment of Tweets by Not Depressed People', bbox={'facecolor':'0.8', 'pad':0})

data_train_sentiment 

In [ ]:
# plotting % of negative tweets 
import numpy as np
import matplotlib.pyplot as plt
 
# set width of bar
barWidth = 0.25
 
# set height of bar
print (len(data_train_sentiment_depressed)/n_pos)
print (len(data_train_sentiment_not_depressed)/n_neg)
bars1 = [len(data_train_sentiment_depressed[data_train_sentiment_depressed.sentiment_type == "NEGATIVE"])/n_pos,len(data_train_sentiment_not_depressed[data_train_sentiment_not_depressed.sentiment_type == "NEGATIVE"])/n_neg]
bars2 = [len(data_train_sentiment_depressed)/n_pos,len(data_train_sentiment_not_depressed)/n_neg]
 
plt.subplot(2,1,1)

# Set position of bar on X axis
r1 = np.arange(len(bars1))
r2 = [x + barWidth for x in r1]
 
# Make the plot
plt.bar(r1, bars1, color='#7f6d5f', width=barWidth, edgecolor='white', label='NEGATIVE SENTIMENT')
plt.bar(r2, bars2, color='#557f2d', width=barWidth, edgecolor='white', label='ALL TWEETS')
 
# Add xticks on the middle of the group bars
plt.xlabel('GROUP', fontweight='bold')
plt.xticks([r + barWidth for r in range(len(bars1))], ['DEPRESSED', 'NOT DEPRESSED'])
 
# Create legend & Show graphic
plt.legend()
plt.show()

In [ ]:
##CALC % of negative tweets
x = np.arange(2)

data = [len(data_train_sentiment_depressed[data_train_sentiment_depressed.sentiment_type == "NEGATIVE"])/len(data_train_sentiment_depressed),
        len(data_train_sentiment_not_depressed[data_train_sentiment_not_depressed.sentiment_type == "NEGATIVE"])/len(data_train_sentiment_not_depressed)]

# Make the plot
plt.bar(x, data,label='Percentage of negative posts')
barWidth = 0.01
# Add xticks on the middle of the group bars
plt.xlabel('GROUP', fontweight='bold')
plt.xticks([r + barWidth for r in range(len(data))], ['DEPRESSED', 'NOT DEPRESSED'])
 
# Create legend & Show graphic
plt.legend()

In [ ]:
x = np.arange(2)
data = [len(data_train_sentiment_depressed)/n_pos,len(data_train_sentiment_not_depressed)/n_neg]

# Make the plot
plt.bar(x, data, label='NUMBER OF POSTS PER USER')
barWidth = 0.01
# Add xticks on the middle of the group bars
plt.xlabel('GROUP', fontweight='bold')
plt.xticks([r+barWidth for r in range(len(data))], ['DEPRESSED', 'NOT DEPRESSED'])
 
# Create legend & Show graphic
plt.legend()
plt.show()

In [ ]:
# Finding I's in text
data_train['text_len_word'] = data_train['text_lem'].apply(lambda x: re.findall(r'(\S+)', x))
data_train['text_len_word'] = data_train['text_len_word'].apply(len)
data_train['text_i'] = data_train['text_lem'].apply(lambda x: re.findall(r'(?:\s|^)i(?=\s|$)', x))
data_train['text_i'] = data_train['text_i'].apply(len)
# Finding what percentage of "i" is of all posts words
data_train['text_i_percent'] = (data_train['text_i']/data_train['text_len_word'])*100


In [ ]:
data_train
#Examining the difference between depressed and non-depressed "i" usage:
per_of_i = data_train.groupby(['depressed'])['text_i_percent'].mean()
per_of_i
#Graphing it:
x = np.arange(2)

data = [per_of_i[1], per_of_i[0]]

# Make the plot
plt.bar(x, data,label='Percentage of I usage in posts')
barWidth = 0.01
# Add xticks on the middle of the group bars
plt.xlabel('GROUP', fontweight='bold')
plt.xticks([r + barWidth for r in range(len(data))], ['DEPRESSED', 'NOT DEPRESSED'])
 
# Create legend & Show graphic
plt.legend()
plt.show()

In [ ]:
abs_words = ["absolutely","all","always","complete","completely","constant","constantly","definitely","entire","ever","every","everyone","everything",
             "full","must","never","nothing","totally","whole"]

def count_absolutist(x):
    sum = 0
    for word in abs_words:
        sum+=x.count(word)
    
    return sum

data_train_grouped['abs'] = data_train_grouped['text_lem'].apply(lambda x: count_absolutist(x))


In [ ]:
data_train_grouped['n_words'] = data_train_grouped['text_lem'].apply(lambda x: len(re.findall(r'\w+', x)))

In [ ]:
#Calculating percentage of absolutist words
data_train_grouped['abs_p'] = (data_train_grouped['abs']/data_train_grouped['n_words'])*100

In [ ]:
# Graphing it
per_of_abs = data_train_grouped.groupby(['depressed'])['abs_p'].mean()
per_of_abs
x = np.arange(2)

data = [per_of_abs[1], per_of_abs[0]]

# Make the plot
plt.bar(x, data,label='Usage of absolutist words in posts by percentage')
barWidth = 0.01
# Add xticks on the middle of the group bars
plt.xlabel('GROUP', fontweight='bold')
plt.xticks([r + barWidth for r in range(len(data))], ['DEPRESSED', 'NOT DEPRESSED'])
 
# Create legend & Show graphic
plt.legend()
plt.show()

In [ ]:
data_train_grouped['w_per_post'] = data_train_grouped['nwords']/data_train_grouped['pos_len']
w_per_post = data_train_grouped.groupby(['depressed'])['w_per_post'].mean()
w_per_post

In [ ]:
x = np.arange(2)
data = [w_per_post[1], w_per_post[0]]

# Make the plot
plt.bar(x, data,label='Average words per post')
barWidth = 0.01
# Add xticks on the middle of the group bars
plt.xlabel('GROUP', fontweight='bold')
plt.xticks([r + barWidth for r in range(len(data))], ['DEPRESSED', 'NOT DEPRESSED'])
 
# Create legend & Show graphic
plt.legend()